# 	Jacob Kurbis (Z1945650)
#	CSCI 340: Data Structures Section: 0003
#	Assignment 2	Due: 02/06/2021
#	
#	I certify that this is my own work and where appropriate an extension 
#	of the starter code provided for the assignment.
#

matrix: main.cc matrix.cc matrix.h
	g++ -std=c++14 -Wall -Werror -Wextra -pedantic -g -o matrix main.cc matrix.cc

clean:
	rm -f matrix

world: clean matrix
